reusable test
Signed-off-by: Christiano <christiano.guedes@zup.com.br>

diff --git a/.github/workflows/create.yml b/.github/workflows/create.yml
--- a/.github/workflows/create.yml
+++ b/.github/workflows/create.yml
@@ -48,9 +48,6 @@ on:
         git:
           description: PAT secret git
           required: true
-env:
-  reusable_workflow_repo: stack-spot/stackspot-workflows-action
-  reusable_workflow_branch: ${{ github.ref_name }} 
 
 jobs:
   validate-inputs:
@@ -97,6 +94,31 @@ jobs:
         run: |
          echo "ERROR: 'email' field not found in json for 'cli_login' input"
          exit 1
+      - name: "Validate Input: 'config.email'"
+        if: fromJson(inputs.config).default_branch == ''
+        run: |
+         echo "ERROR: 'default_branch' field not found in json for 'config' input"
+         exit 1
+      - name: "Validate Input: 'config.debug'"
+        if: fromJson(inputs.config).debug == ''
+        run: |
+         echo "ERROR: 'debug' field not found in json for 'config' input"
+         exit 1
+      - name: "Validate Input: 'config.stk'"
+        if: fromJson(inputs.config).stk == ''
+        run: |
+         echo "ERROR: 'stk' field not found in json for 'config' input"
+         exit 1
+      - name: "Validate Input: 'config.origin_repository'"
+        if: fromJson(inputs.config).origin_repository == ''
+        run: |
+         echo "ERROR: 'origin_repository' field not found in json for 'config' input"
+         exit 1
+      - name: "Validate Input: 'config.origin_repository'"
+        if: fromJson(inputs.config).origin_branch == ''
+        run: |
+         echo "ERROR: 'origin_branch' field not found in json for 'config' input"
+         exit 1
 
 
   use-workspace:
@@ -109,7 +131,8 @@ jobs:
       - name: Checkout workflows repo
         uses: actions/checkout@v3
         with:
-          repository: ${{ env.reusable_workflow_repo }}
+          repository: ${{ fromJson(inputs.config).origin_repository }}
+          ref: ${{ fromJson(inputs.config).origin_branch }}     
       - name: Cache
         uses: ./github-actions/restore-stk-cache
         with: 
@@ -145,8 +168,8 @@ jobs:
       - name: Checkout workflows repo
         uses: actions/checkout@v3
         with:
-          repository: ${{ env.reusable_workflow_repo }}
-          branch: 
+          repository: ${{ fromJson(inputs.config).origin_repository }}
+          ref: ${{ fromJson(inputs.config).origin_branch }}
       - name: Restore STK Cache
         uses: ./github-actions/restore-stk-cache
         with: 
@@ -181,7 +204,8 @@ jobs:
       - name: Checkout workflows repo
         uses: actions/checkout@v3
         with:
-          repository: ${{ env.reusable_workflow_repo }}
+          repository: ${{ fromJson(inputs.config).origin_repository }}
+          ref: ${{ fromJson(inputs.config).origin_branch }}
           persist-credentials: false
           path: workflow_repo
       - name: Checkout the user repo
@@ -271,7 +295,8 @@ jobs:
         with:
           persist-credentials: false
           path: workflow_repo
-          repository: ${{ env.reusable_workflow_repo }}
+          repository: ${{ fromJson(inputs.config).origin_repository }}
+          ref: ${{ fromJson(inputs.config).origin_branch }}
       - name: Checkout the user repo
         id: checkout_user_repo
         uses:  ./workflow_repo/github-actions/clone-external-repo
